version: '3.3'
services:

  frontend:
    image: holohup/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static/
      - media_value:/var/html/media/

    depends_on:
      backend:
        condition: service_healthy

    restart: unless-stopped
    healthcheck:
      test: curl -fs http://localhost/admin/ || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  db:
    image: postgres:13.0-alpine
    volumes:
      - ~/foodgram/data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'pg_isready']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s

  backend:
    image: holohup/foodgram_backend:latest
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - static_value:/app/static/
      - media_value:/app/media/
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ['CMD', 'python', 'manage.py', 'check']
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 60s

volumes:
  static_value:
  media_value:
  db_data: