# Generated by Django 2.2.16 on 2023-02-05 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230205_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_carts', to='recipes.Recipe', verbose_name='Recipe in shopping cart'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shop_carts', to=settings.AUTH_USER_MODEL, verbose_name='Shopping cart user'),
        ),
        migrations.AlterIndexTogether(
            name='ingredient',
            index_together=set(),
        ),
    ]
