# Generated by Django 2.2.16 on 2023-01-18 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_auto_20230118_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='Ingredient name'),
        ),
    ]
