# Generated by Django 2.2.16 on 2023-01-29 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20230129_1829'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Tag', 'verbose_name_plural': 'Tags'},
        ),
        migrations.AlterField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=7, unique=True, validators=[django.core.validators.RegexValidator(code='incorrect_hex_color', message='Incorrect HEX color.', regex='^#[A-Fa-f0-9]{6}$')], verbose_name='color'),
        ),
    ]
